// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZdpc_aQcnSh5WNRgAai9QuiSxlD1QNUI',
    appId: '1:300686522146:web:50f7fa5b86cfead548577b',
    messagingSenderId: '300686522146',
    projectId: 'aerox-stage1',
    authDomain: 'aerox-stage1.firebaseapp.com',
    storageBucket: 'aerox-stage1.firebasestorage.app',
    measurementId: 'G-26G1K09S7J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCq0QBGnbdyMWfLCJi2sdoqDNZfigbLPlo',
    appId: '1:300686522146:android:adc15c3a2362217648577b',
    messagingSenderId: '300686522146',
    projectId: 'aerox-stage1',
    storageBucket: 'aerox-stage1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkl13kogJtqN6k7vUnJtjB5yq7F7QbNd8',
    appId: '1:300686522146:ios:ef8e930edcc38c6848577b',
    messagingSenderId: '300686522146',
    projectId: 'aerox-stage1',
    storageBucket: 'aerox-stage1.firebasestorage.app',
    iosClientId: '300686522146-qp9qu6rc5grtj32logdff36kfld5tvgl.apps.googleusercontent.com',
    iosBundleId: 'com.labtend.aerox.stage1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkl13kogJtqN6k7vUnJtjB5yq7F7QbNd8',
    appId: '1:300686522146:ios:816152deb7236e2548577b',
    messagingSenderId: '300686522146',
    projectId: 'aerox-stage1',
    storageBucket: 'aerox-stage1.firebasestorage.app',
    iosClientId: '300686522146-hb4b68nh4iq98964dtsrcpn25f1u682r.apps.googleusercontent.com',
    iosBundleId: 'com.example.aeroxStage1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZdpc_aQcnSh5WNRgAai9QuiSxlD1QNUI',
    appId: '1:300686522146:web:04e6aa5419f8609348577b',
    messagingSenderId: '300686522146',
    projectId: 'aerox-stage1',
    authDomain: 'aerox-stage1.firebaseapp.com',
    storageBucket: 'aerox-stage1.firebasestorage.app',
    measurementId: 'G-FMQLD8HTS9',
  );

}