// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4Iww_cFKDu5wnXhTXYYEVKEH3xvx7JLM',
    appId: '1:293842013726:web:0578a7e8d5b82a54cc280f',
    messagingSenderId: '293842013726',
    projectId: 'aerox-1',
    authDomain: 'aerox-1.firebaseapp.com',
    storageBucket: 'aerox-1.firebasestorage.app',
    measurementId: 'G-9057W4DTXD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoBZLTSwOeKDRA_TxVpOiqjjjut7J4PPE',
    appId: '1:293842013726:android:70ed409487b67204cc280f',
    messagingSenderId: '293842013726',
    projectId: 'aerox-1',
    storageBucket: 'aerox-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5kziInLPEJOEbIZnn968YX1TFGbNzajQ',
    appId: '1:293842013726:ios:590434cad3c4f67ecc280f',
    messagingSenderId: '293842013726',
    projectId: 'aerox-1',
    storageBucket: 'aerox-1.firebasestorage.app',
    androidClientId: '293842013726-tl96rs5t8k25ot5is38en5grqo1q613j.apps.googleusercontent.com',
    iosClientId: '293842013726-u5f5qkc2278es3t9riliafqv6150hl7v.apps.googleusercontent.com',
    iosBundleId: 'com.labtend.aerox',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5kziInLPEJOEbIZnn968YX1TFGbNzajQ',
    appId: '1:293842013726:ios:04e35618b4031ac2cc280f',
    messagingSenderId: '293842013726',
    projectId: 'aerox-1',
    storageBucket: 'aerox-1.firebasestorage.app',
    androidClientId: '293842013726-tl96rs5t8k25ot5is38en5grqo1q613j.apps.googleusercontent.com',
    iosClientId: '293842013726-ed1ie2r1mvlr0657arldsadeqjb5cc3d.apps.googleusercontent.com',
    iosBundleId: 'com.example.aeroxStage1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4Iww_cFKDu5wnXhTXYYEVKEH3xvx7JLM',
    appId: '1:293842013726:web:c8b8d0b766927f76cc280f',
    messagingSenderId: '293842013726',
    projectId: 'aerox-1',
    authDomain: 'aerox-1.firebaseapp.com',
    storageBucket: 'aerox-1.firebasestorage.app',
    measurementId: 'G-MS3QP5Y7C9',
  );

}